"""empty message

Revision ID: cb102327bd5d
Revises: 
Create Date: 2021-05-28 22:41:28.840151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb102327bd5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
